export const COURSE_PATH = '/danh-sach-khoa-hoc';
export const COURSE_DETAIL_PATH = '/thong-tin-khoa-hoc';
export const ABOUT_PATH = '/ve-chung-toi';
export const CONTACT_PATH = '/lien-he';
export const ACCOUNT_PATH = '/tai-khoan';
export const REGISTER_PATH = '/dang-ky';
export const LOGIN_PATH = '/dang-nhap';
export const INSTRUCTORS_PATH = '/giang-vien';
export const BLOG_PATH = '/blog-list';
export const COURSE_REGISTER = '/ghi-danh-khoa-hoc';
export const COURSE_SEARCH_PATH = '/tim-kiem';

// ****** ADMIN ****** //
export const ADMIN_PARENT = '/admin';
export const USER_MANAGER_PATH = 'quan-ly-nguoi-dung';
export const USER_CREATE_EDIT_PATH = 'thong-tin-nguoi-dung';
export const COURSE_MANAGER_PATH = 'quan-ly-khoa-hoc';
export const ADMIN_LOGIN_PATH = '/admin/dang-nhap';
export const ACCOUNT_ADMIN_PATH = 'thong-tin-tai-khoan';
